from __future__ import annotations

import os
import signal
import socket
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

from . import cli, commands, config, health, net, process
from .cli import _add_frontend_args, _add_server_args, _build_parser, main
from .commands import (
    ProgressReporter,
    RunCommand,
    _console_progress,
    _report_progress,
    check_frontend_start_preconditions,
    deploy,
    install,
    restart,
    start,
    start_frontend,
    start_server,
    status,
    status_frontend,
    status_server,
    stop,
    stop_frontend,
    stop_server,
)
from .config import (
    DEFAULT_FRONTEND_HOST,
    DEFAULT_FRONTEND_PORT,
    DEFAULT_HEALTH_TIMEOUT_SECONDS,
    DEFAULT_HOST,
    DEFAULT_PORT,
    PROFILE_DEFAULT_PORTS,
    REMOVED_CONFIG_ENV_NAMES,
    SKIP_STARTUP_DB_BOOTSTRAP_ENV,
    SUPPORTED_INFERENCE_BACKENDS,
    _command_env,
    _configured_log_path,
    _format_log_file,
    _frontend_env,
    _is_deepseek_model,
    _is_openai_compatible_model,
    _profile_settings,
    _reject_removed_config_env,
    _require_file,
    _require_local_venv,
    _resolve_backend_port,
    _tool_path,
    _unquote_env_value,
    load_profile_env,
    require_profile_config,
    validate_profile_config,
)
from .errors import ServctlError
from .health import (
    _preflight_probe_path,
    _preflight_python_code,
    _run_python_probe,
    _tail_lines,
    run_preflight_checks,
    wait_for_frontend,
    wait_for_health,
)
from .net import (
    _ensure_port_available,
    _http_url,
    _is_port_in_use,
    _probe_host,
    _probe_port,
    _wait_for_port_release,
)
from .process import (
    RUN_DIR_NAME,
    FrontendProcessConfig,
    ServerProcessConfig,
    _frontend_log_path,
    _frontend_pid_path,
    _frontend_process_config,
    _log_path,
    _pid_path,
    _prepare_log_file,
    _process_exists,
    _read_pid,
    _server_process_config,
    _status_pid_file_process,
    _stop_pid_file_process,
    _terminate_process,
    _write_pid,
    spawn_frontend_process,
    spawn_server_process,
)

__all__ = [
    "DEFAULT_FRONTEND_HOST",
    "DEFAULT_FRONTEND_PORT",
    "DEFAULT_HEALTH_TIMEOUT_SECONDS",
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "FrontendProcessConfig",
    "PROFILE_DEFAULT_PORTS",
    "Path",
    "ProgressReporter",
    "REMOVED_CONFIG_ENV_NAMES",
    "RUN_DIR_NAME",
    "RunCommand",
    "SKIP_STARTUP_DB_BOOTSTRAP_ENV",
    "SUPPORTED_INFERENCE_BACKENDS",
    "ServerProcessConfig",
    "ServctlError",
    "_add_frontend_args",
    "_add_server_args",
    "_build_parser",
    "_command_env",
    "_configured_log_path",
    "_console_progress",
    "_ensure_port_available",
    "_format_log_file",
    "_frontend_env",
    "_frontend_log_path",
    "_frontend_pid_path",
    "_frontend_process_config",
    "_http_url",
    "_is_deepseek_model",
    "_is_openai_compatible_model",
    "_is_port_in_use",
    "_log_path",
    "_pid_path",
    "_preflight_probe_path",
    "_preflight_python_code",
    "_prepare_log_file",
    "_probe_host",
    "_probe_port",
    "_process_exists",
    "_profile_settings",
    "_read_pid",
    "_reject_removed_config_env",
    "_report_progress",
    "_require_file",
    "_require_local_venv",
    "_resolve_backend_port",
    "_run_python_probe",
    "_server_process_config",
    "_status_pid_file_process",
    "_stop_pid_file_process",
    "_tail_lines",
    "_terminate_process",
    "_tool_path",
    "_unquote_env_value",
    "_wait_for_port_release",
    "_write_pid",
    "check_frontend_start_preconditions",
    "cli",
    "commands",
    "config",
    "deploy",
    "health",
    "install",
    "load_profile_env",
    "main",
    "net",
    "os",
    "process",
    "require_profile_config",
    "restart",
    "run_preflight_checks",
    "signal",
    "socket",
    "spawn_frontend_process",
    "spawn_server_process",
    "start",
    "start_frontend",
    "start_server",
    "status",
    "status_frontend",
    "status_server",
    "stop",
    "stop_frontend",
    "stop_server",
    "subprocess",
    "time",
    "urllib",
    "validate_profile_config",
    "wait_for_frontend",
    "wait_for_health",
]
